"""add_webhook_models

Revision ID: 7439e234eea3
Revises: af6abb54460f
Create Date: 2026-07-30 17:54:30.143892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7439e234eea3'
down_revision: Union[str, Sequence[str], None] = 'af6abb54460f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_subscription',
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('events', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_delivery',
    sa.Column('webhook_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook_subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_webhook_id'), 'webhook_delivery', ['webhook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_delivery_webhook_id'), table_name='webhook_delivery')
    op.drop_table('webhook_delivery')
    op.drop_table('webhook_subscription')
    # ### end Alembic commands ###
