"""add OAuth fields and make hashed_password nullable

Revision ID: 83d049b52a5d
Revises: e1271c647f4a
Create Date: 2026-07-24 16:35:48.712456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d049b52a5d'
down_revision: Union[str, Sequence[str], None] = 'e1271c647f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('github_id', sa.String(length=255), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['github_id'])
    op.create_unique_constraint(None, 'user', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'github_id')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###
