"""add 2fa fields and backup_code model

Revision ID: a59197c12cbc
Revises: 84d1838a111d
Create Date: 2026-07-24 16:28:48.235503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59197c12cbc'
down_revision: Union[str, Sequence[str], None] = '84d1838a111d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'totp_secret')
    op.drop_column('user', 'is_2fa_enabled')
    # ### end Alembic commands ###
